import React from "react";

const randomQuotes = [
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "Do what you feel in your heart to be right—for you’ll be criticized anyway.", author: "Eleanor Roosevelt" },
    { quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
    { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown(LORD KRISHNA)" },
    { quote: "The best way to predict the future is to create it.", author: "Peter Drucker" },
    { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { quote: "Do what you love and you’ll never work a day in your life.", author: "Marc Anthony" },
    { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    { quote: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
    { quote: "An unexamined life is not worth living.", author: "Socrates" },
    { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { quote: "When everything seems to be going against you, remember that the airplane takes off against the wind.", author: "Henry Ford" },
    { quote: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "If you judge people, you have no time to love them.", author: "Mother Teresa" },
    { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { quote: "Love the life you live. Live the life you love.", author: "Bob Marley" },
    { quote: "When one door closes, another opens.", author: "Alexander Graham Bell" },
    { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
    { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { quote: "It always seems impossible until it is done.", author: "Nelson Mandela" },
  { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { quote: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "If opportunity doesn't knock, build a door.", author: "Milton Berle" },
  { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { quote: "You can’t cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
  { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
  { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
  { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { quote: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "Life isn’t about getting and having, it’s about giving and being.", author: "Kevin Kruse" },
  { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { quote: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown" },
  { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { quote: "Don't wait. The time will never be just right.", author: "Napoleon Hill" },
  { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
  { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
  { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
  { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
  { quote: "Make each day your masterpiece.", author: "John Wooden" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Anonymous" },
  { quote: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { quote: "Let your smile change the world, but don’t let the world change your smile.", author: "Connor Franta" }
  ];

export default randomQuotes;
